import type {
  Produto,
  Cliente,
  Venda,
  FaturamentoDiario,
} from '@/tipos'

function calcularMargem(custo: number, preco: number): number {
  return ((preco - custo) / preco) * 100
}

function calcularMarkup(custo: number, preco: number): number {
  return ((preco - custo) / custo) * 100
}

export const produtosMock: Produto[] = [
  {
    id: 'prod-001',
    nome: 'Recomeços',
    intencao: 'Para quem busca um novo começo com leveza e clareza mental',
    tipoCera: 'vegetal-soja',
    granulometria: 'fina',
    gramagem: 200,
    notasAromaticas: {
      topo: 'Alecrim',
      coracao: 'Palo Santo',
      fundo: 'Baunilha',
    },
    percentualFragrancia: 8,
    tipoPavio: 'algodao',
    corCera: '#F5F0E8',
    recipiente: 'Pote de vidro âmbar 200ml',
    tempoQueima: 40,
    custoProducao: 18,
    precoVenda: 68,
    margem: calcularMargem(18, 68),
    markup: calcularMarkup(18, 68),
    categoria: 'para-rituais',
    tags: ['renovação', 'limpeza energética', 'alecrim'],
    estoqueAtual: 12,
    estoqueMinimo: 5,
    descricaoCurta: 'Uma vela para marcar o início de um novo ciclo com intenção e presença.',
    historiaVela: 'Nasceu do desejo de criar um ritual de transição. O alecrim purifica, o Palo Santo abre caminhos e a baunilha acolhe o novo que chega.',
    ativo: true,
    criadoEm: new Date('2024-01-15'),
    atualizadoEm: new Date('2024-11-10'),
  },
  {
    id: 'prod-002',
    nome: 'Silêncio',
    intencao: 'Para momentos de meditação e conexão interior profunda',
    tipoCera: 'vegetal-soja',
    granulometria: 'fina',
    gramagem: 180,
    notasAromaticas: {
      topo: 'Sândalo',
      coracao: 'Cedro',
      fundo: 'Almíscar',
    },
    percentualFragrancia: 7,
    tipoPavio: 'madeira',
    corCera: '#EDE5D0',
    recipiente: 'Pote de cerâmica off-white 180ml',
    tempoQueima: 35,
    custoProducao: 16,
    precoVenda: 59,
    margem: calcularMargem(16, 59),
    markup: calcularMarkup(16, 59),
    categoria: 'para-rituais',
    tags: ['meditação', 'silêncio', 'introspecção'],
    estoqueAtual: 8,
    estoqueMinimo: 5,
    descricaoCurta: 'O silêncio tem cheiro. Este é ele.',
    historiaVela: 'Desenvolvida para acompanhar práticas meditativas. O crepitar suave do pavio de madeira convida ao recolhimento.',
    ativo: true,
    criadoEm: new Date('2024-02-01'),
    atualizadoEm: new Date('2024-11-05'),
  },
  {
    id: 'prod-003',
    nome: 'Euforia',
    intencao: 'Para celebrar a alegria de estar viva e presente',
    tipoCera: 'mista',
    granulometria: 'media',
    gramagem: 200,
    notasAromaticas: {
      topo: 'Laranja',
      coracao: 'Gengibre',
      fundo: 'Ylang Ylang',
    },
    percentualFragrancia: 9,
    tipoPavio: 'duplo',
    corCera: '#F2C97B',
    recipiente: 'Pote de vidro transparente 200ml',
    tempoQueima: 38,
    custoProducao: 19,
    precoVenda: 72,
    margem: calcularMargem(19, 72),
    markup: calcularMarkup(19, 72),
    categoria: 'uso-diario',
    tags: ['alegria', 'energia', 'cítrico'],
    estoqueAtual: 15,
    estoqueMinimo: 5,
    descricaoCurta: 'A mais animada da coleção. Acenda e deixe a energia tomar conta do ambiente.',
    historiaVela: 'Uma explosão de alegria em cera. A laranja desperta, o gengibre aquece e o ylang ylang prolonga o prazer.',
    ativo: true,
    criadoEm: new Date('2024-03-10'),
    atualizadoEm: new Date('2024-10-28'),
  },
  {
    id: 'prod-004',
    nome: 'Pertencimento',
    intencao: 'Para criar um lar onde o coração se sente em paz',
    tipoCera: 'vegetal-coco',
    granulometria: 'fina',
    gramagem: 220,
    notasAromaticas: {
      topo: 'Rosa',
      coracao: 'Patchouli',
      fundo: 'Baunilha',
    },
    percentualFragrancia: 10,
    tipoPavio: 'algodao',
    corCera: '#EADAD8',
    recipiente: 'Pote de vidro rosé 220ml',
    tempoQueima: 45,
    custoProducao: 22,
    precoVenda: 85,
    margem: calcularMargem(22, 85),
    markup: calcularMarkup(22, 85),
    categoria: 'para-presentes',
    tags: ['lar', 'aconchego', 'presente', 'rosa'],
    estoqueAtual: 3,
    estoqueMinimo: 5,
    descricaoCurta: 'Uma declaração de amor ao lugar onde você escolhe existir.',
    historiaVela: 'A vela favorita das mães e das que presenteiam com carinho. A rosa abraça, o patchouli enraíza e a baunilha transforma qualquer espaço em lar.',
    ativo: true,
    criadoEm: new Date('2024-04-05'),
    atualizadoEm: new Date('2024-11-01'),
  },
  {
    id: 'prod-005',
    nome: 'Descanso',
    intencao: 'Para o ritual da noite e uma noite de sono profundo',
    tipoCera: 'vegetal-soja',
    granulometria: 'fina',
    gramagem: 180,
    notasAromaticas: {
      topo: 'Lavanda',
      coracao: 'Camomila',
      fundo: 'Bergamota',
    },
    percentualFragrancia: 8,
    tipoPavio: 'algodao',
    corCera: '#E8E4F0',
    recipiente: 'Pote de vidro lilás 180ml',
    tempoQueima: 35,
    custoProducao: 15,
    precoVenda: 55,
    margem: calcularMargem(15, 55),
    markup: calcularMarkup(15, 55),
    categoria: 'uso-diario',
    tags: ['sono', 'relaxamento', 'lavanda', 'noite'],
    estoqueAtual: 20,
    estoqueMinimo: 5,
    descricaoCurta: 'O convite mais gentil ao sono que você já recebeu.',
    historiaVela: 'Criada para o momento em que o dia termina e o corpo pede cuidado. Lavanda e camomila acalmam a mente; a bergamota suaviza a transição.',
    ativo: true,
    criadoEm: new Date('2024-01-20'),
    atualizadoEm: new Date('2024-10-15'),
  },
  {
    id: 'prod-006',
    nome: 'Coragem',
    intencao: 'Para os momentos em que você precisa lembrar do seu próprio poder',
    tipoCera: 'mista',
    granulometria: 'grossa',
    gramagem: 200,
    notasAromaticas: {
      topo: 'Pimenta Rosa',
      coracao: 'Vetiver',
      fundo: 'Cedro',
    },
    percentualFragrancia: 9,
    tipoPavio: 'madeira',
    corCera: '#2C2C2A',
    recipiente: 'Pote de concreto preto 200ml',
    tempoQueima: 42,
    custoProducao: 20,
    precoVenda: 75,
    margem: calcularMargem(20, 75),
    markup: calcularMarkup(20, 75),
    categoria: 'colecao-especial',
    tags: ['força', 'poder', 'decisão', 'especial'],
    estoqueAtual: 2,
    estoqueMinimo: 5,
    descricaoCurta: 'Para acender antes das grandes decisões e dos passos que assustam.',
    historiaVela: 'A mais ousada da coleção. Pimenta rosa para o ímpeto, vetiver para os pés no chão e cedro para a firmeza que dura.',
    ativo: true,
    criadoEm: new Date('2024-06-01'),
    atualizadoEm: new Date('2024-11-08'),
  },
]

export const clientesMock: Cliente[] = [
  {
    id: 'cli-001',
    nomeCompleto: 'Fernanda Oliveira Rezende',
    email: 'fernanda.rezende@gmail.com',
    whatsapp: '(62) 99234-5671',
    canalOrigem: 'instagram',
    endereco: {
      cep: '74230-010',
      logradouro: 'Rua T-30',
      numero: '142',
      complemento: 'Apto 302',
      bairro: 'Setor Bueno',
      cidade: 'Goiânia',
      uf: 'GO',
    },
    observacoesInternas: 'Prefere velas com notas florais. Compra sempre no Dia das Mães.',
    criadoEm: new Date('2024-03-12'),
  },
  {
    id: 'cli-002',
    nomeCompleto: 'Mariana Castilho Borges',
    email: 'mari.borges@hotmail.com',
    whatsapp: '(62) 98765-4321',
    canalOrigem: 'indicacao',
    endereco: {
      cep: '74210-090',
      logradouro: 'Rua 22',
      numero: '78',
      bairro: 'Setor Oeste',
      cidade: 'Goiânia',
      uf: 'GO',
    },
    criadoEm: new Date('2024-04-20'),
  },
  {
    id: 'cli-003',
    nomeCompleto: 'Patrícia Sousa Mendonça',
    email: 'patricia.mendonca@yahoo.com.br',
    whatsapp: '(62) 99112-3344',
    canalOrigem: 'feira',
    endereco: {
      cep: '74650-010',
      logradouro: 'Av. Universitária',
      numero: '1512',
      complemento: 'Casa',
      bairro: 'Setor Universitário',
      cidade: 'Goiânia',
      uf: 'GO',
    },
    observacoesInternas: 'Conheceu na Feira Hippie. Compra para revender em ateliê.',
    criadoEm: new Date('2024-05-08'),
  },
  {
    id: 'cli-004',
    nomeCompleto: 'Juliana Ferreira Prado',
    email: 'ju.prado@gmail.com',
    whatsapp: '(62) 99876-5540',
    canalOrigem: 'instagram',
    endereco: {
      cep: '75110-010',
      logradouro: 'Rua Barão do Rio Branco',
      numero: '305',
      bairro: 'Centro',
      cidade: 'Anápolis',
      uf: 'GO',
    },
    criadoEm: new Date('2024-06-15'),
  },
  {
    id: 'cli-005',
    nomeCompleto: 'Renata Vieira Albuquerque',
    email: 'renata.albuquerque@gmail.com',
    whatsapp: '(62) 99001-7823',
    canalOrigem: 'instagram',
    endereco: {
      cep: '74810-100',
      logradouro: 'Rua C-149',
      numero: '55',
      bairro: 'Jardim América',
      cidade: 'Goiânia',
      uf: 'GO',
    },
    criadoEm: new Date('2024-07-22'),
  },
  {
    id: 'cli-006',
    nomeCompleto: 'Ana Carolina Teixeira',
    email: 'anacarol.teixeira@outlook.com',
    whatsapp: '(61) 99345-6789',
    canalOrigem: 'site',
    endereco: {
      cep: '70070-010',
      logradouro: 'SQN 208',
      numero: 'Bloco C',
      bairro: 'Asa Norte',
      cidade: 'Brasília',
      uf: 'DF',
    },
    observacoesInternas: 'Compra por presente. Prefere embalagem premium.',
    criadoEm: new Date('2024-08-03'),
  },
  {
    id: 'cli-007',
    nomeCompleto: 'Camila Rodrigues Nogueira',
    email: 'camila.nogueira@gmail.com',
    whatsapp: '(62) 98890-1122',
    canalOrigem: 'whatsapp',
    endereco: {
      cep: '75600-010',
      logradouro: 'Av. Brasil',
      numero: '874',
      bairro: 'Setor Central',
      cidade: 'Rio Verde',
      uf: 'GO',
    },
    criadoEm: new Date('2024-09-14'),
  },
  {
    id: 'cli-008',
    nomeCompleto: 'Isabela Martins Fontes',
    email: 'isa.fontes@gmail.com',
    whatsapp: '(62) 99654-3210',
    canalOrigem: 'indicacao',
    endereco: {
      cep: '74170-120',
      logradouro: 'Rua 14 de Julho',
      numero: '220',
      complemento: 'Casa 2',
      bairro: 'Setor Marista',
      cidade: 'Goiânia',
      uf: 'GO',
    },
    observacoesInternas: 'Indicada pela Fernanda. Faz pedidos mensais regulares.',
    criadoEm: new Date('2024-10-05'),
  },
]

export const vendasMock: Venda[] = [
  {
    id: 'vda-001',
    numeroPedido: 'PSQ-000001',
    clienteId: 'cli-001',
    itens: [
      { produtoId: 'prod-004', nomeProduto: 'Pertencimento', quantidade: 2, precoUnitario: 85, subtotal: 170 },
      { produtoId: 'prod-005', nomeProduto: 'Descanso', quantidade: 1, precoUnitario: 55, subtotal: 55 },
    ],
    desconto: 0,
    total: 225,
    canalVenda: 'instagram',
    formaPagamento: 'pix',
    statusPagamento: 'pago',
    tipoEntrega: 'correios',
    statusEntrega: 'entregue',
    criadoEm: new Date('2024-10-05'),
  },
  {
    id: 'vda-002',
    numeroPedido: 'PSQ-000002',
    clienteId: 'cli-003',
    itens: [
      { produtoId: 'prod-001', nomeProduto: 'Recomeços', quantidade: 3, precoUnitario: 68, subtotal: 204 },
      { produtoId: 'prod-006', nomeProduto: 'Coragem', quantidade: 2, precoUnitario: 75, subtotal: 150 },
    ],
    desconto: 20,
    total: 334,
    canalVenda: 'whatsapp',
    formaPagamento: 'pix',
    statusPagamento: 'pago',
    tipoEntrega: 'retirada',
    statusEntrega: 'entregue',
    criadoEm: new Date('2024-10-12'),
  },
  {
    id: 'vda-003',
    numeroPedido: 'PSQ-000003',
    clienteId: 'cli-006',
    itens: [
      { produtoId: 'prod-004', nomeProduto: 'Pertencimento', quantidade: 1, precoUnitario: 85, subtotal: 85 },
    ],
    desconto: 0,
    total: 85,
    canalVenda: 'site',
    formaPagamento: 'cartao-credito',
    statusPagamento: 'pago',
    tipoEntrega: 'correios',
    statusEntrega: 'entregue',
    criadoEm: new Date('2024-10-18'),
  },
  {
    id: 'vda-004',
    numeroPedido: 'PSQ-000004',
    clienteId: 'cli-002',
    itens: [
      { produtoId: 'prod-003', nomeProduto: 'Euforia', quantidade: 2, precoUnitario: 72, subtotal: 144 },
      { produtoId: 'prod-002', nomeProduto: 'Silêncio', quantidade: 1, precoUnitario: 59, subtotal: 59 },
    ],
    desconto: 0,
    total: 203,
    canalVenda: 'instagram',
    formaPagamento: 'pix',
    statusPagamento: 'pago',
    tipoEntrega: 'motoboy',
    statusEntrega: 'entregue',
    criadoEm: new Date('2024-10-25'),
  },
  {
    id: 'vda-005',
    numeroPedido: 'PSQ-000005',
    itens: [
      { produtoId: 'prod-005', nomeProduto: 'Descanso', quantidade: 2, precoUnitario: 55, subtotal: 110 },
    ],
    desconto: 0,
    total: 110,
    canalVenda: 'presencial',
    formaPagamento: 'dinheiro',
    statusPagamento: 'pago',
    tipoEntrega: 'retirada',
    statusEntrega: 'entregue',
    criadoEm: new Date('2024-11-02'),
  },
  {
    id: 'vda-006',
    numeroPedido: 'PSQ-000006',
    clienteId: 'cli-007',
    itens: [
      { produtoId: 'prod-001', nomeProduto: 'Recomeços', quantidade: 1, precoUnitario: 68, subtotal: 68 },
      { produtoId: 'prod-006', nomeProduto: 'Coragem', quantidade: 1, precoUnitario: 75, subtotal: 75 },
    ],
    desconto: 0,
    total: 143,
    canalVenda: 'marketplace',
    formaPagamento: 'cartao-credito',
    statusPagamento: 'pago',
    tipoEntrega: 'correios',
    statusEntrega: 'enviado',
    criadoEm: new Date('2024-11-05'),
  },
  {
    id: 'vda-007',
    numeroPedido: 'PSQ-000007',
    clienteId: 'cli-008',
    itens: [
      { produtoId: 'prod-005', nomeProduto: 'Descanso', quantidade: 2, precoUnitario: 55, subtotal: 110 },
      { produtoId: 'prod-004', nomeProduto: 'Pertencimento', quantidade: 1, precoUnitario: 85, subtotal: 85 },
      { produtoId: 'prod-002', nomeProduto: 'Silêncio', quantidade: 1, precoUnitario: 59, subtotal: 59 },
    ],
    desconto: 15,
    total: 239,
    canalVenda: 'whatsapp',
    formaPagamento: 'pix',
    statusPagamento: 'pago',
    tipoEntrega: 'motoboy',
    statusEntrega: 'entregue',
    criadoEm: new Date('2024-11-08'),
  },
  {
    id: 'vda-008',
    numeroPedido: 'PSQ-000008',
    clienteId: 'cli-004',
    itens: [
      { produtoId: 'prod-003', nomeProduto: 'Euforia', quantidade: 3, precoUnitario: 72, subtotal: 216 },
    ],
    desconto: 0,
    total: 216,
    canalVenda: 'instagram',
    formaPagamento: 'pix',
    statusPagamento: 'pendente',
    tipoEntrega: 'correios',
    statusEntrega: 'em-producao',
    criadoEm: new Date('2024-11-10'),
  },
  {
    id: 'vda-009',
    numeroPedido: 'PSQ-000009',
    clienteId: 'cli-005',
    itens: [
      { produtoId: 'prod-001', nomeProduto: 'Recomeços', quantidade: 2, precoUnitario: 68, subtotal: 136 },
    ],
    desconto: 0,
    total: 136,
    canalVenda: 'site',
    formaPagamento: 'cartao-debito',
    statusPagamento: 'pago',
    tipoEntrega: 'correios',
    statusEntrega: 'aguardando',
    criadoEm: new Date('2024-11-11'),
  },
  {
    id: 'vda-010',
    numeroPedido: 'PSQ-000010',
    itens: [
      { produtoId: 'prod-006', nomeProduto: 'Coragem', quantidade: 1, precoUnitario: 75, subtotal: 75 },
      { produtoId: 'prod-003', nomeProduto: 'Euforia', quantidade: 1, precoUnitario: 72, subtotal: 72 },
    ],
    desconto: 0,
    total: 147,
    canalVenda: 'presencial',
    formaPagamento: 'cartao-debito',
    statusPagamento: 'pago',
    tipoEntrega: 'retirada',
    statusEntrega: 'entregue',
    criadoEm: new Date('2024-11-12'),
  },
]

function gerarFaturamentoDiario(): FaturamentoDiario[] {
  const dados: FaturamentoDiario[] = []
  const hoje = new Date('2024-11-12')
  const baseValor = 180

  for (let i = 29; i >= 0; i--) {
    const data = new Date(hoje)
    data.setDate(hoje.getDate() - i)

    const tendencia = ((29 - i) / 29) * 80
    const variacao = (Math.sin(i * 1.3) * 40) + (Math.cos(i * 0.7) * 25)
    const valor = Math.max(0, baseValor + tendencia + variacao)

    dados.push({
      data,
      valor: Math.round(valor * 10) / 10,
    })
  }

  return dados
}

export const dadosFaturamentoDiario: FaturamentoDiario[] = gerarFaturamentoDiario()
